plugins: [jekyll-paginate]

permalink: /:categories/:title/

highlighter: rouge
markdown: kramdown
kramdown:
  input:  GFM
  syntax_highlighter: rouge


paginate: 10
paginate_path: "page/:num"
baseurl: "https://bulingfeng.com/"



defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      styles : [highlight.css,gitment.css,post.css]
      scripts : [gitment.js, post.js]



title: "我爱吻篮板"
email: lingfeng.lucky@gmail.com
description: ""
github:
  username: bulingfeng
swiftype:
  searchId: CzzNW78uCqEiLsmB8yqN
gitment:
    repo: bulingfeng.github.io
    client_id: 1bece54ee79aa1efc585
    client_secret: 24140c9089bc8244231fc67a3bf9ea27811f7cd1

url: "http://bulingfeng.com/"
imgrepo: "https://bulingfeng.github.io/static/img"


#url: "http://127.0.0.1:4000"
#imgrepo: "http://127.0.0.1:4000/static/img"

